### ISSUE TITLE
Host should be derived from API key

### ISSUE THREAD

**Issue by dawesi** [akitogo/mailchimpV3#2]
by using listLast(apikey,'-') you can obtain the dc for the mailchimp account

the hard coded references to us1 can then be removed permanently.
eg:
`https://us1.api.mailchimp.com/3.0/`

should be:
`https://#dc#.api.mailchimp.com/3.0/` - put appropriate variable here

**Comment by GunnarLieb** [comment]
Please see line 25 in Mailchimp.cfc. It's already there

**Comment by GunnarLieb** [comment]
Will add comment to cfc
